// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: nav

/*
    Copyright (c) 2024 Felix Biego. All rights reserved.
    This work is licensed under the terms of the MIT license.
    For a copy, see <https://opensource.org/licenses/MIT>.
*/

#include "navigation.h"

#ifdef ENABLE_APP_NAVIGATION

#include <ctype.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>

#if defined(TTGO_TDISPLAY) || defined(WAVESHARE_S3_LCD_154) || defined(ESP32_TOUCH_LCD_35)
/* "Rẽ phải về hướng Võ Thị Sáu" -> first line up to/including "về hướng", tên đường ở dòng 2 */
static bool nav_split_ve_huong(const char *in, char *out, size_t out_len)
{
    if (in == NULL || out == NULL || out_len < 4) {
        return false;
    }
    static const char *const keys[] = {"về hướng", "Về hướng"};
    for (unsigned k = 0; k < sizeof(keys) / sizeof(keys[0]); k++) {
        const char *p = strstr(in, keys[k]);
        if (p == NULL) {
            continue;
        }
        size_t klen = strlen(keys[k]);
        const char *rest = p + klen;
        while (*rest == ' ') {
            rest++;
        }
        if (*rest == '\0') {
            return false;
        }
        size_t line1_bytes = (size_t)(p - in) + klen;
        size_t line2_len = strlen(rest);
        if (line1_bytes + 1 + line2_len + 1 > out_len) {
            return false;
        }
        memcpy(out, in, line1_bytes);
        out[line1_bytes] = '\n';
        memcpy(out + line1_bytes + 1, rest, line2_len + 1);
        return true;
    }
    return false;
}
#endif

LV_FONT_DECLARE(lv_font_nav_vn_16);
LV_FONT_DECLARE(lv_font_nav_vn_20);
LV_FONT_DECLARE(lv_font_nav_vn_30);
LV_FONT_DECLARE(lv_font_montserrat_14);
LV_FONT_DECLARE(lv_font_montserrat_16);

#define CANVAS_WIDTH 48
#define CANVAS_HEIGHT 48

REGISTER_APP("Navigation", &ui_img_arrow_png, ui_navScreen, ui_navScreen_screen_init);

lv_obj_t *ui_navPanel;
lv_obj_t *ui_navDirection;
lv_obj_t *ui_navText;
lv_obj_t *ui_navDistance;
lv_obj_t *ui_navIconCanvas;
lv_obj_t *ui_navIcon;
lv_obj_t *ui_navTitle;

#if defined(ESP32_TOUCH_LCD_35) && !defined(NAVIGATION_UI_LEGACY)
static lv_obj_t *ui_navV2_clock_lbl;
static lv_obj_t *ui_navV2_map_box;
static lv_obj_t *ui_navV2_prog_bar;
static lv_obj_t *ui_navV2_trip_dur_val;
static lv_obj_t *ui_navV2_trip_dist_val;
static lv_obj_t *ui_navV2_trip_eta_val;

/* App may send nav.eta like "Dự kiến 11:20" — show HH:MM only when parsable */
static void nav_ws35_format_eta_time(const char *raw, char *out, size_t out_len)
{
    if (out == NULL || out_len == 0) {
        return;
    }
    out[0] = '\0';
    if (raw == NULL || raw[0] == '\0') {
        snprintf(out, out_len, "-");
        return;
    }
    for (const char *p = raw; *p != '\0'; p++) {
        if (!isdigit((unsigned char)*p)) {
            continue;
        }
        int hh = 0, mm = 0, consumed = 0;
        if (sscanf(p, "%d:%d%n", &hh, &mm, &consumed) != 2 || consumed < 3) {
            continue;
        }
        if (hh < 0 || hh > 23 || mm < 0 || mm > 59) {
            continue;
        }
        snprintf(out, out_len, "%02d:%02d", hh, mm);
        return;
    }
    const char *s = raw;
    if (strncmp(s, "ETA ", 4) == 0) {
        s += 4;
    }
    while (*s == ' ' || *s == '\t') {
        s++;
    }
    snprintf(out, out_len, "%s", s);
    if (out_len > 0) {
        out[out_len - 1] = '\0';
    }
}

/* Trip cells: fixed outer column height; shrink font by UTF-8 length so long strings still fit */
static void nav_ws35_trip_label_autofit(lv_obj_t *lbl, const char *txt)
{
    if (lbl == NULL) {
        return;
    }
    lv_label_set_text(lbl, txt);
    size_t n = strlen(txt);
    const lv_font_t *f = &lv_font_nav_vn_30;
    if (n > 36U) {
        f = &lv_font_nav_vn_16;
    } else if (n > 22U) {
        f = &lv_font_nav_vn_20;
    } else {
        f = &lv_font_nav_vn_30;
    }
    lv_obj_set_style_text_font(lbl, f, LV_PART_MAIN | LV_STATE_DEFAULT);
}

static lv_obj_t *nav_ws35_trip_col_value_only(lv_obj_t *parent, lv_obj_t **val_out)
{
    lv_obj_t *c = lv_obj_create(parent);
    lv_obj_set_flex_grow(c, 1);
    lv_obj_set_height(c, lv_pct(100));
    lv_obj_set_flex_flow(c, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(c, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_opa(c, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_width(c, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(c, 2, LV_PART_MAIN);
    *val_out = lv_label_create(c);
    lv_label_set_text(*val_out, "-");
    lv_obj_set_width(*val_out, lv_pct(100));
    lv_label_set_long_mode(*val_out, LV_LABEL_LONG_DOT);
    lv_obj_set_style_text_align(*val_out, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(*val_out, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    nav_ws35_trip_label_autofit(*val_out, "-");
    return c;
}

static void nav_ws35_v2_apply_info(const char *text, const char *title, const char *directions)
{
    const char *t = title != NULL ? title : "";
    /* ui_navDistance kept hidden for API parity with other boards */
    if (ui_navDistance != NULL) {
        lv_label_set_text(ui_navDistance, t[0] ? t : "-");
    }

    /* Top of text column: distance to maneuver (large green) */
    lv_label_set_text(ui_navTitle, t[0] ? t : "-");

    /* Below: full instruction / street (two lines when "về hướng" split applies) */
    if (ui_navDirection != NULL) {
        static char dir_buf[320];
        const char *d = directions != NULL ? directions : "";
        if (d[0] != '\0' && nav_split_ve_huong(d, dir_buf, sizeof(dir_buf))) {
            lv_label_set_text(ui_navDirection, dir_buf);
        } else {
            lv_label_set_text(ui_navDirection, d);
        }
        lv_obj_remove_flag(ui_navDirection, LV_OBJ_FLAG_HIDDEN);
    }

    (void)text;
}
#endif

void ui_event_navScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START)
    {
    }
    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        onGameOpened();
    }
    // if (event_code == LV_EVENT_SCREEN_UNLOAD_START)
    // {
    //     qmi8658c_active = false;
    // }
    if (event_code == LV_EVENT_SCREEN_UNLOADED)
    {
        onGameClosed();
    }

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT)
    {
        ui_app_exit();
    }
}

void ui_navScreen_screen_init()
{
    if (ui_navScreen != NULL)
    {
        return;
    }

    ui_navScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_navScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_navScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

#if defined(WAVESHARE_S3_LCD_154)
    {
        lv_coord_t W = lv_display_get_horizontal_resolution(lv_display_get_default());
        lv_coord_t H = lv_display_get_vertical_resolution(lv_display_get_default());
        if (W < 10) W = 240;
        if (H < 10) H = 240;

        ui_navPanel = lv_obj_create(ui_navScreen);
        lv_obj_set_size(ui_navPanel, W, H);
        lv_obj_set_align(ui_navPanel, LV_ALIGN_CENTER);
        lv_obj_remove_flag(ui_navPanel, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_radius(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_navPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_navPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_left(ui_navPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_right(ui_navPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_top(ui_navPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_bottom(ui_navPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_navText = lv_label_create(ui_navPanel); /* ETA + duration + distance */
        lv_obj_set_width(ui_navText, lv_pct(100));
        lv_obj_set_align(ui_navText, LV_ALIGN_TOP_MID);
        lv_label_set_long_mode(ui_navText, LV_LABEL_LONG_WRAP);
        lv_label_set_text(ui_navText, "Navigation");
        lv_obj_set_style_text_align(ui_navText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navText, &lv_font_nav_vn_16, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navText, lv_color_hex(0x00BFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_bottom(ui_navText, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

        /* Reserve ~52px for 2 lines of vn_16 + padding so icon does not overlap ETA */
        static const lv_coord_t ws154_icon_y = 56;

        LV_DRAW_BUF_DEFINE_STATIC(cbuf_ws154, CANVAS_WIDTH, CANVAS_HEIGHT, LV_COLOR_FORMAT_I2);
        LV_DRAW_BUF_INIT_STATIC(cbuf_ws154);
        ui_navIconCanvas = lv_canvas_create(ui_navPanel);
        lv_canvas_set_draw_buf(ui_navIconCanvas, &cbuf_ws154);
        lv_obj_set_width(ui_navIconCanvas, 48);
        lv_obj_set_height(ui_navIconCanvas, 48);
        lv_obj_set_y(ui_navIconCanvas, ws154_icon_y);
        lv_obj_set_align(ui_navIconCanvas, LV_ALIGN_TOP_MID);
        lv_obj_remove_flag(ui_navIconCanvas, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_radius(ui_navIconCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_navIconCanvas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_navIconCanvas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_navIconCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_canvas_fill_bg(ui_navIconCanvas, lv_color_black(), LV_OPA_COVER);
        lv_canvas_set_palette(ui_navIconCanvas, 0, lv_color32_make(0, 0, 0, 255));
        lv_canvas_set_palette(ui_navIconCanvas, 1, lv_color32_make(255, 255, 255, 255));

        ui_navIcon = lv_image_create(ui_navPanel);
        lv_image_set_src(ui_navIcon, &ui_img_chronos_logo_png);
        lv_obj_set_y(ui_navIcon, ws154_icon_y);
        lv_obj_set_align(ui_navIcon, LV_ALIGN_TOP_MID);
        lv_obj_remove_flag(ui_navIcon, LV_OBJ_FLAG_SCROLLABLE);

        ui_navDistance = lv_label_create(ui_navPanel); /* title / road */
        lv_obj_set_width(ui_navDistance, lv_pct(100));
        lv_obj_set_y(ui_navDistance, ws154_icon_y + 48 + 8);
        lv_obj_set_align(ui_navDistance, LV_ALIGN_TOP_MID);
        lv_label_set_long_mode(ui_navDistance, LV_LABEL_LONG_WRAP);
        lv_label_set_text(ui_navDistance, "Chronos");
        lv_obj_set_style_text_align(ui_navDistance, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navDistance, &lv_font_nav_vn_20, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navDistance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_navDirection = lv_label_create(ui_navPanel); /* turn instruction */
        lv_obj_set_width(ui_navDirection, lv_pct(100));
        lv_obj_set_height(ui_navDirection, 72);
        /* ~52px for up to 2 lines of vn_20 title above directions */
        lv_obj_set_y(ui_navDirection, ws154_icon_y + 48 + 8 + 52);
        lv_obj_set_align(ui_navDirection, LV_ALIGN_TOP_MID);
        lv_label_set_long_mode(ui_navDirection, LV_LABEL_LONG_WRAP);
        lv_label_set_text(ui_navDirection, "Available on v3.7.5+");
        lv_obj_set_style_text_align(ui_navDirection, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navDirection, &lv_font_nav_vn_20, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navDirection, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
#elif defined(ESP32_TOUCH_LCD_35) && !defined(NAVIGATION_UI_LEGACY)
    {
        /* Navigation V2 — wireframe support/wireframe-v2.txt (status | icon+road+bar | distance | trip 3-col) */
        lv_coord_t W = lv_display_get_horizontal_resolution(lv_display_get_default());
        lv_coord_t H = lv_display_get_vertical_resolution(lv_display_get_default());
        if (W < 10) {
            W = 480;
        }
        if (H < 10) {
            H = 320;
        }

        ui_navPanel = lv_obj_create(ui_navScreen);
        lv_obj_set_size(ui_navPanel, W, H);
        lv_obj_set_align(ui_navPanel, LV_ALIGN_CENTER);
        lv_obj_remove_flag(ui_navPanel, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_flex_flow(ui_navPanel, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(ui_navPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
        lv_obj_set_style_radius(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_navPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_navPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_left(ui_navPanel, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_right(ui_navPanel, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_top(ui_navPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_bottom(ui_navPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_row(ui_navPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

        /* Status bar: clock only */
        lv_obj_t *stat = lv_obj_create(ui_navPanel);
        lv_obj_set_width(stat, lv_pct(100));
        lv_obj_set_height(stat, 34);
        lv_obj_set_flex_flow(stat, LV_FLEX_FLOW_ROW);
        lv_obj_set_flex_align(stat, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_set_style_bg_opa(stat, LV_OPA_TRANSP, LV_PART_MAIN);
        lv_obj_set_style_border_width(stat, 0, LV_PART_MAIN);
        lv_obj_set_style_pad_all(stat, 0, LV_PART_MAIN);

        ui_navV2_clock_lbl = lv_label_create(stat);
        lv_label_set_text(ui_navV2_clock_lbl, "-- : --");
        lv_obj_set_width(ui_navV2_clock_lbl, lv_pct(100));
        lv_obj_set_style_text_align(ui_navV2_clock_lbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navV2_clock_lbl, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navV2_clock_lbl, lv_color_hex(0xFFF8E1), LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_navDistance = lv_label_create(ui_navPanel);
        lv_obj_add_flag(ui_navDistance, LV_OBJ_FLAG_HIDDEN);
        lv_label_set_text(ui_navDistance, "-");

        lv_obj_t *center = lv_obj_create(ui_navPanel);
        lv_obj_set_width(center, lv_pct(100));
        lv_obj_set_flex_grow(center, 1);
        lv_obj_set_flex_flow(center, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(center, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
        lv_obj_set_style_pad_row(center, 4, LV_PART_MAIN);
        lv_obj_set_style_bg_opa(center, LV_OPA_TRANSP, LV_PART_MAIN);
        lv_obj_set_style_border_width(center, 0, LV_PART_MAIN);
        lv_obj_set_style_pad_all(center, 0, LV_PART_MAIN);

        lv_obj_t *mid_top = lv_obj_create(center);
        lv_obj_set_width(mid_top, lv_pct(100));
        lv_obj_set_flex_grow(mid_top, 1);
        lv_obj_set_height(mid_top, 120);
        lv_obj_set_flex_flow(mid_top, LV_FLEX_FLOW_ROW);
        lv_obj_set_flex_align(mid_top, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
        lv_obj_set_style_pad_column(mid_top, 12, LV_PART_MAIN);
        lv_obj_set_style_bg_opa(mid_top, LV_OPA_TRANSP, LV_PART_MAIN);
        lv_obj_set_style_border_width(mid_top, 0, LV_PART_MAIN);
        lv_obj_set_style_pad_all(mid_top, 0, LV_PART_MAIN);

        lv_obj_t *icon_col = lv_obj_create(mid_top);
        lv_obj_set_width(icon_col, 128);
        lv_obj_set_height(icon_col, lv_pct(100));
        lv_obj_set_flex_flow(icon_col, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(icon_col, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_set_style_bg_opa(icon_col, LV_OPA_TRANSP, LV_PART_MAIN);
        lv_obj_set_style_border_width(icon_col, 0, LV_PART_MAIN);
        lv_obj_set_style_pad_all(icon_col, 0, LV_PART_MAIN);

        ui_navV2_map_box = lv_obj_create(icon_col);
        lv_obj_set_width(ui_navV2_map_box, lv_pct(100));
        lv_obj_set_height(ui_navV2_map_box, 118);
        lv_obj_set_flex_flow(ui_navV2_map_box, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(ui_navV2_map_box, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_set_style_bg_color(ui_navV2_map_box, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_navV2_map_box, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_navV2_map_box, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_navV2_map_box, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_navV2_map_box, lv_color_hex(0x5F6368), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_all(ui_navV2_map_box, 10, LV_PART_MAIN);

        LV_DRAW_BUF_DEFINE_STATIC(cbuf_ws35, CANVAS_WIDTH, CANVAS_HEIGHT, LV_COLOR_FORMAT_I2);
        LV_DRAW_BUF_INIT_STATIC(cbuf_ws35);
        ui_navIconCanvas = lv_canvas_create(ui_navV2_map_box);
        lv_canvas_set_draw_buf(ui_navIconCanvas, &cbuf_ws35);
        lv_obj_set_size(ui_navIconCanvas, 48, 48);
        lv_obj_remove_flag(ui_navIconCanvas, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_radius(ui_navIconCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_navIconCanvas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_navIconCanvas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_navIconCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_canvas_fill_bg(ui_navIconCanvas, lv_color_black(), LV_OPA_COVER);
        lv_canvas_set_palette(ui_navIconCanvas, 0, lv_color32_make(0, 0, 0, 255));
        lv_canvas_set_palette(ui_navIconCanvas, 1, lv_color32_make(255, 255, 255, 255));

        ui_navIcon = lv_image_create(ui_navV2_map_box);
        lv_image_set_src(ui_navIcon, &ui_img_chronos_logo_png);
        lv_obj_remove_flag(ui_navIcon, LV_OBJ_FLAG_SCROLLABLE);

        lv_obj_t *txt_col = lv_obj_create(mid_top);
        lv_obj_set_flex_grow(txt_col, 1);
        lv_obj_set_height(txt_col, lv_pct(100));
        lv_obj_set_flex_flow(txt_col, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(txt_col, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
        lv_obj_set_style_pad_row(txt_col, 8, LV_PART_MAIN);
        lv_obj_set_style_bg_opa(txt_col, LV_OPA_TRANSP, LV_PART_MAIN);
        lv_obj_set_style_border_width(txt_col, 0, LV_PART_MAIN);
        lv_obj_set_style_pad_all(txt_col, 0, LV_PART_MAIN);

        ui_navTitle = lv_label_create(txt_col);
        lv_label_set_text(ui_navTitle, "");
        lv_obj_set_width(ui_navTitle, lv_pct(100));
        lv_label_set_long_mode(ui_navTitle, LV_LABEL_LONG_DOT);
        lv_obj_set_style_text_align(ui_navTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navTitle, &lv_font_nav_vn_30, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navTitle, lv_color_hex(0x34A853), LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_navDirection = lv_label_create(txt_col);
        lv_label_set_text(ui_navDirection, "");
        lv_obj_set_width(ui_navDirection, lv_pct(100));
        lv_obj_set_height(ui_navDirection, 56);
        lv_obj_set_flex_grow(ui_navDirection, 1);
        lv_label_set_long_mode(ui_navDirection, LV_LABEL_LONG_WRAP);
        lv_obj_set_style_text_align(ui_navDirection, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navDirection, &lv_font_nav_vn_20, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navDirection, lv_color_hex(0xE8EAED), LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_navText = lv_label_create(ui_navPanel);
        lv_obj_add_flag(ui_navText, LV_OBJ_FLAG_HIDDEN);
        lv_label_set_text(ui_navText, "");

        /* Trip info: 3 equal columns + thin vertical dividers */
        lv_obj_t *trip = lv_obj_create(ui_navPanel);
        lv_obj_set_width(trip, lv_pct(100));
        lv_obj_set_height(trip, 56);
        lv_obj_set_flex_flow(trip, LV_FLEX_FLOW_ROW);
        lv_obj_set_flex_align(trip, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_set_style_bg_color(trip, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(trip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(trip, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(trip, 0, LV_PART_MAIN);
        lv_obj_set_style_pad_left(trip, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_right(trip, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_top(trip, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_bottom(trip, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

        nav_ws35_trip_col_value_only(trip, &ui_navV2_trip_dur_val);
        lv_obj_t *div1 = lv_obj_create(trip);
        lv_obj_set_width(div1, 1);
        lv_obj_set_height(div1, 40);
        lv_obj_set_style_bg_color(div1, lv_color_hex(0x3C4043), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(div1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(div1, 0, LV_PART_MAIN);
        nav_ws35_trip_col_value_only(trip, &ui_navV2_trip_dist_val);
        lv_obj_t *div2 = lv_obj_create(trip);
        lv_obj_set_width(div2, 1);
        lv_obj_set_height(div2, 40);
        lv_obj_set_style_bg_color(div2, lv_color_hex(0x3C4043), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(div2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(div2, 0, LV_PART_MAIN);
        nav_ws35_trip_col_value_only(trip, &ui_navV2_trip_eta_val);

        /* Segment progress: Chronos nav packet has no progress field (vantc-navi keynote §5.1); bar reserved for future app extension */
        ui_navV2_prog_bar = lv_bar_create(ui_navPanel);
        lv_obj_set_width(ui_navV2_prog_bar, lv_pct(100));
        lv_obj_set_height(ui_navV2_prog_bar, 8);
        lv_bar_set_range(ui_navV2_prog_bar, 0, 1000);
        lv_bar_set_value(ui_navV2_prog_bar, 0, LV_ANIM_OFF);
        lv_obj_set_style_radius(ui_navV2_prog_bar, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_navV2_prog_bar, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_radius(ui_navV2_prog_bar, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_navV2_prog_bar, lv_color_hex(0x34A853), LV_PART_INDICATOR | LV_STATE_DEFAULT);

        lv_obj_set_style_bg_color(ui_navScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_navScreen, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
#elif defined(ESP32_TOUCH_LCD_35) && defined(NAVIGATION_UI_LEGACY)
    {
        /* Legacy rectangular Navigation (ETA row + icon + title + directions), full panel */
        lv_coord_t W = lv_display_get_horizontal_resolution(lv_display_get_default());
        lv_coord_t H = lv_display_get_vertical_resolution(lv_display_get_default());
        if (W < 10) {
            W = 480;
        }
        if (H < 10) {
            H = 320;
        }

        ui_navPanel = lv_obj_create(ui_navScreen);
        lv_obj_set_size(ui_navPanel, W, H);
        lv_obj_set_align(ui_navPanel, LV_ALIGN_CENTER);
        lv_obj_remove_flag(ui_navPanel, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_radius(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_navPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_navPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_left(ui_navPanel, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_right(ui_navPanel, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_top(ui_navPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_bottom(ui_navPanel, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_navText = lv_label_create(ui_navPanel); /* ETA + duration + distance */
        lv_obj_set_width(ui_navText, lv_pct(100));
        lv_obj_set_align(ui_navText, LV_ALIGN_TOP_MID);
        lv_label_set_long_mode(ui_navText, LV_LABEL_LONG_WRAP);
        lv_label_set_text(ui_navText, "Navigation");
        lv_obj_set_style_text_align(ui_navText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navText, &lv_font_nav_vn_16, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navText, lv_color_hex(0x00BFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_bottom(ui_navText, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

        static const lv_coord_t legacy_icon_y = 58;

        LV_DRAW_BUF_DEFINE_STATIC(cbuf_ws35leg, CANVAS_WIDTH, CANVAS_HEIGHT, LV_COLOR_FORMAT_I2);
        LV_DRAW_BUF_INIT_STATIC(cbuf_ws35leg);
        ui_navIconCanvas = lv_canvas_create(ui_navPanel);
        lv_canvas_set_draw_buf(ui_navIconCanvas, &cbuf_ws35leg);
        lv_obj_set_width(ui_navIconCanvas, 48);
        lv_obj_set_height(ui_navIconCanvas, 48);
        lv_obj_set_y(ui_navIconCanvas, legacy_icon_y);
        lv_obj_set_align(ui_navIconCanvas, LV_ALIGN_TOP_MID);
        lv_obj_remove_flag(ui_navIconCanvas, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_radius(ui_navIconCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_navIconCanvas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_navIconCanvas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_navIconCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_canvas_fill_bg(ui_navIconCanvas, lv_color_black(), LV_OPA_COVER);
        lv_canvas_set_palette(ui_navIconCanvas, 0, lv_color32_make(0, 0, 0, 255));
        lv_canvas_set_palette(ui_navIconCanvas, 1, lv_color32_make(255, 255, 255, 255));

        ui_navIcon = lv_image_create(ui_navPanel);
        lv_image_set_src(ui_navIcon, &ui_img_chronos_logo_png);
        lv_obj_set_y(ui_navIcon, legacy_icon_y);
        lv_obj_set_align(ui_navIcon, LV_ALIGN_TOP_MID);
        lv_obj_remove_flag(ui_navIcon, LV_OBJ_FLAG_SCROLLABLE);

        ui_navDistance = lv_label_create(ui_navPanel); /* title / road */
        lv_obj_set_width(ui_navDistance, lv_pct(100));
        lv_obj_set_y(ui_navDistance, legacy_icon_y + 48 + 10);
        lv_obj_set_align(ui_navDistance, LV_ALIGN_TOP_MID);
        lv_label_set_long_mode(ui_navDistance, LV_LABEL_LONG_WRAP);
        lv_label_set_text(ui_navDistance, "Chronos");
        lv_obj_set_style_text_align(ui_navDistance, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navDistance, &lv_font_nav_vn_20, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navDistance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_navDirection = lv_label_create(ui_navPanel); /* turn instruction */
        lv_obj_set_width(ui_navDirection, lv_pct(100));
        lv_obj_set_height(ui_navDirection, LV_SIZE_CONTENT);
        lv_obj_set_y(ui_navDirection, legacy_icon_y + 48 + 10 + 56);
        lv_obj_set_align(ui_navDirection, LV_ALIGN_TOP_MID);
        lv_label_set_long_mode(ui_navDirection, LV_LABEL_LONG_WRAP);
        lv_label_set_text(ui_navDirection, "Available on v3.7.5+");
        lv_obj_set_style_text_align(ui_navDirection, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navDirection, &lv_font_nav_vn_20, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navDirection, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
#elif !defined(TTGO_TDISPLAY)
    ui_navPanel = lv_obj_create(ui_navScreen);
    lv_obj_set_width(ui_navPanel, 240);
    lv_obj_set_height(ui_navPanel, 240);
    lv_obj_set_align(ui_navPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_navPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_navPanel, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_navPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navDirection = lv_label_create(ui_navPanel);
    lv_obj_set_width(ui_navDirection, 200);
    lv_obj_set_height(ui_navDirection, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_navDirection, 0);
    lv_obj_set_y(ui_navDirection, 158);
    lv_obj_set_align(ui_navDirection, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_navDirection, LV_LABEL_LONG_WRAP);
    lv_label_set_text(ui_navDirection, "Available on v3.7.5+");
    lv_obj_set_style_text_align(ui_navDirection, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_navDirection, &lv_font_nav_vn_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navText = lv_label_create(ui_navPanel);
    lv_obj_set_width(ui_navText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_navText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_navText, 0);
    lv_obj_set_y(ui_navText, 12);
    lv_obj_set_align(ui_navText, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_navText, "Navigation\nESP32 only");
    lv_obj_set_style_text_align(ui_navText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_navText, &lv_font_nav_vn_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navDistance = lv_label_create(ui_navPanel);
    lv_obj_set_width(ui_navDistance, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_navDistance, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_navDistance, 0);
    lv_obj_set_y(ui_navDistance, 128);
    lv_obj_set_align(ui_navDistance, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_navDistance, "Chronos");
    lv_obj_set_style_text_font(ui_navDistance, &lv_font_nav_vn_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    LV_DRAW_BUF_DEFINE_STATIC(cbuf, CANVAS_WIDTH, CANVAS_HEIGHT, LV_COLOR_FORMAT_I2);
    LV_DRAW_BUF_INIT_STATIC(cbuf);

    ui_navIconCanvas = lv_canvas_create(ui_navPanel);
    lv_canvas_set_draw_buf(ui_navIconCanvas, &cbuf);
    lv_obj_set_width(ui_navIconCanvas, 48);
    lv_obj_set_height(ui_navIconCanvas, 48);
    lv_obj_set_x(ui_navIconCanvas, 0);
    lv_obj_set_y(ui_navIconCanvas, 76);
    lv_obj_set_align(ui_navIconCanvas, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_navIconCanvas, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_navIconCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_navIconCanvas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navIconCanvas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_navIconCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_canvas_fill_bg(ui_navIconCanvas, lv_color_black(), LV_OPA_COVER);
    lv_canvas_set_palette(ui_navIconCanvas, 0, lv_color32_make(0, 0, 0, 255));
    lv_canvas_set_palette(ui_navIconCanvas, 1, lv_color32_make(255, 255, 255, 255));

    ui_navIcon = lv_image_create(ui_navPanel);
    lv_image_set_src(ui_navIcon, &ui_img_chronos_logo_png);
    lv_obj_set_width(ui_navIcon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_navIcon, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_navIcon, 0);
    lv_obj_set_y(ui_navIcon, 76);
    lv_obj_set_align(ui_navIcon, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_navIcon, LV_OBJ_FLAG_SCROLLABLE); /// Flags
#else
    {
        lv_coord_t W = lv_display_get_horizontal_resolution(lv_display_get_default());
        lv_coord_t H = lv_display_get_vertical_resolution(lv_display_get_default());
        if (W < 10) W = 240;
        if (H < 10) H = 135;
        ui_navPanel = lv_obj_create(ui_navScreen);
        lv_obj_set_size(ui_navPanel, W, H);
        lv_obj_set_align(ui_navPanel, LV_ALIGN_CENTER);
        lv_obj_remove_flag(ui_navPanel, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_radius(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_navPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_navPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_pad_all(ui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_flex_flow(ui_navPanel, LV_FLEX_FLOW_ROW);
        /* Main: start, Cross: center — keep row vertically centered in panel */
        lv_obj_set_flex_align(ui_navPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_set_style_pad_column(ui_navPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

        lv_obj_t *left = lv_obj_create(ui_navPanel);
        lv_obj_set_size(left, 56, H);
        lv_obj_set_flex_flow(left, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(left, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
        lv_obj_set_style_bg_opa(left, LV_OPA_TRANSP, LV_PART_MAIN);
        lv_obj_set_style_border_width(left, 0, LV_PART_MAIN);
        lv_obj_set_style_pad_all(left, 0, LV_PART_MAIN);

        LV_DRAW_BUF_DEFINE_STATIC(cbuf_ttgo, CANVAS_WIDTH, CANVAS_HEIGHT, LV_COLOR_FORMAT_I2);
        LV_DRAW_BUF_INIT_STATIC(cbuf_ttgo);
        ui_navIconCanvas = lv_canvas_create(left);
        lv_canvas_set_draw_buf(ui_navIconCanvas, &cbuf_ttgo);
        lv_obj_set_width(ui_navIconCanvas, 48);
        lv_obj_set_height(ui_navIconCanvas, 48);
        lv_obj_remove_flag(ui_navIconCanvas, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_radius(ui_navIconCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_navIconCanvas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_navIconCanvas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_width(ui_navIconCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_canvas_fill_bg(ui_navIconCanvas, lv_color_black(), LV_OPA_COVER);
        lv_canvas_set_palette(ui_navIconCanvas, 0, lv_color32_make(0, 0, 0, 255));
        lv_canvas_set_palette(ui_navIconCanvas, 1, lv_color32_make(255, 255, 255, 255));

        ui_navIcon = lv_image_create(left);
        lv_image_set_src(ui_navIcon, &ui_img_chronos_logo_png);
        lv_obj_remove_flag(ui_navIcon, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_bg_opa(ui_navIcon, LV_OPA_TRANSP, LV_PART_MAIN);

        /* flex_grow fills remaining width; do not use width 100% here — it confuses the row
         * and can give the right column 0px so labels render invisible. */
        lv_obj_t *rcol = lv_obj_create(ui_navPanel);
        lv_obj_set_flex_grow(rcol, 1);
        lv_obj_set_flex_flow(rcol, LV_FLEX_FLOW_COLUMN);
        lv_obj_set_flex_align(rcol, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
        lv_obj_set_height(rcol, lv_pct(100));
        lv_obj_set_style_bg_opa(rcol, LV_OPA_TRANSP, LV_PART_MAIN);
        lv_obj_set_style_border_width(rcol, 0, LV_PART_MAIN);
        lv_obj_set_style_pad_row(rcol, 3, LV_PART_MAIN);
        lv_obj_set_style_pad_all(rcol, 0, LV_PART_MAIN);

        /* navigateInfo: title -> ui_navDistance, text -> ui_navText, directions -> ui_navDirection */
        ui_navDistance = lv_label_create(rcol);
        lv_label_set_text(ui_navDistance, "Chronos");
        lv_obj_set_width(ui_navDistance, lv_pct(100));
        lv_label_set_long_mode(ui_navDistance, LV_LABEL_LONG_WRAP);
        lv_obj_set_style_text_align(ui_navDistance, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navDistance, &lv_font_nav_vn_20, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navDistance, lv_color_hex(0x00BFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_navText = lv_label_create(rcol);
        lv_label_set_text(ui_navText, "Navigation");
        lv_obj_set_width(ui_navText, lv_pct(100));
        lv_label_set_long_mode(ui_navText, LV_LABEL_LONG_WRAP);
        lv_obj_set_style_text_align(ui_navText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navText, &lv_font_nav_vn_16, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_navDirection = lv_label_create(rcol);
        lv_label_set_text(ui_navDirection, "—");
        lv_obj_set_width(ui_navDirection, lv_pct(100));
        lv_obj_set_flex_grow(ui_navDirection, 1);
        lv_label_set_long_mode(ui_navDirection, LV_LABEL_LONG_WRAP);
        lv_obj_set_style_text_align(ui_navDirection, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_navDirection, &lv_font_nav_vn_20, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_navDirection, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
#endif

    lv_obj_add_event_cb(ui_navScreen, ui_event_navScreen, LV_EVENT_ALL, NULL);

}

#endif

void navigateInfo(const char *text, const char *title, const char *directions)
{
#ifdef ENABLE_APP_NAVIGATION
    if (!ui_navScreen){
        return;
    }
    lv_label_set_text(ui_navText, text);
#if defined(ESP32_TOUCH_LCD_35) && !defined(NAVIGATION_UI_LEGACY)
    nav_ws35_v2_apply_info(text, title, directions);
#elif defined(TTGO_TDISPLAY) || defined(WAVESHARE_S3_LCD_154) || (defined(ESP32_TOUCH_LCD_35) && defined(NAVIGATION_UI_LEGACY))
    {
        const char *d = directions != NULL ? directions : "";
        static char dir_two_line[320];
        if (d[0] && nav_split_ve_huong(d, dir_two_line, sizeof(dir_two_line))) {
            lv_label_set_text(ui_navDirection, dir_two_line);
        } else {
            lv_label_set_text(ui_navDirection, d);
        }
    }
    lv_label_set_text(ui_navDistance, title);
#else
    lv_label_set_text(ui_navDirection, directions != NULL ? directions : "");
    lv_label_set_text(ui_navDistance, title);
#endif

#endif
}

#ifdef ENABLE_APP_NAVIGATION
void navigation_refresh_status_bar(const char *clock_hm, int notif_cnt, int call_cnt, bool ble_ok, uint8_t phone_batt_pct, bool wifi_ok)
{
#if defined(ESP32_TOUCH_LCD_35) && !defined(NAVIGATION_UI_LEGACY)
    (void)notif_cnt;
    (void)call_cnt;
    (void)ble_ok;
    (void)phone_batt_pct;
    (void)wifi_ok;
    if (!ui_navScreen || ui_navV2_clock_lbl == NULL) {
        return;
    }
    lv_label_set_text(ui_navV2_clock_lbl, clock_hm != NULL ? clock_hm : "-- : --");
    lv_obj_set_style_text_color(ui_navV2_clock_lbl, lv_color_hex(0xFFF8E1), LV_PART_MAIN | LV_STATE_DEFAULT);
#else
    (void)clock_hm;
    (void)notif_cnt;
    (void)call_cnt;
    (void)ble_ok;
    (void)phone_batt_pct;
    (void)wifi_ok;
#endif
}
#if defined(ESP32_TOUCH_LCD_35) && !defined(NAVIGATION_UI_LEGACY)
void navigation_ws35_set_trip_row(const char *eta_raw, const char *duration, const char *distance)
{
    if (ui_navV2_trip_dur_val == NULL) {
        return;
    }
    static char eta_disp[80];
    nav_ws35_format_eta_time(eta_raw != NULL ? eta_raw : "", eta_disp, sizeof(eta_disp));
    static const char dash[] = "-";
    const char *dur = (duration != NULL && duration[0] != '\0') ? duration : dash;
    const char *dist = (distance != NULL && distance[0] != '\0') ? distance : dash;
    nav_ws35_trip_label_autofit(ui_navV2_trip_dur_val, dur);
    nav_ws35_trip_label_autofit(ui_navV2_trip_dist_val, dist);
    nav_ws35_trip_label_autofit(ui_navV2_trip_eta_val, (eta_disp[0] != '\0') ? eta_disp : dash);
}
#endif
#endif

void navIconState(bool show)
{
#ifdef ENABLE_APP_NAVIGATION
    if (!ui_navScreen){
        return;
    }
    if (show)
    {
        lv_obj_remove_flag(ui_navIconCanvas, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_navIcon, LV_OBJ_FLAG_HIDDEN);
    }
    else
    {
        lv_obj_add_flag(ui_navIconCanvas, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(ui_navIcon, LV_OBJ_FLAG_HIDDEN);
    }
#endif
}

void setNavIconPx(uint16_t x, uint16_t y, bool on)
{
#ifdef ENABLE_APP_NAVIGATION
    if (!ui_navScreen){
        return;
    }
    if (on)
    {

        lv_canvas_set_px(ui_navIconCanvas, x, y, lv_color_make(255, 255, 255), LV_OPA_COVER);
    }
    else
    {
        lv_canvas_set_px(ui_navIconCanvas, x, y, lv_color_make(0, 0, 0), LV_OPA_COVER);
    }
#endif
}

lv_obj_t *get_nav_screen(void)
{
#ifdef ENABLE_APP_NAVIGATION
    return ui_navScreen;
#else
    return NULL;
#endif
}
